name: Company Reputation - Analysis

on:
  workflow_dispatch:
  schedule:
      - cron: "0 9 * * *"

env:
  API_KEY: ${{secrets.API_KEY}}
  API_KEY_SECRET: ${{secrets.API_KEY_SECRET}}
  BEARER_TOKEN: ${{secrets.BEARER_TOKEN}}

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Add project root to PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$PWD" >> $GITHUB_ENV
    - name: Test with pytest
      run: |
        echo "API_KEY=${{secrets.API_KEY}}" >> $GITHUB_ENV
        echo "API_KEY_SECRET=${{secrets.API_KEY_SECRET}}" >> $GITHUB_ENV
        echo "BEARER_TOKEN=${{secrets.BEARER_TOKEN}}" >> $GITHUB_ENV
        echo "HF_TOKEN=${{secrets.HF_TOKEN}}" >> $GITHUB_ENV
        pytest
    - name: Analyze Data
      working-directory: "analysis"
      run: |
        python analisi.py
